### ISSUE TITLE
Wrong pose visualizing /aruco_poses in Rviz2

### ISSUE THREAD

**Issue by Veilkrand** [JMU-ROBOTICS-VIVA/ros2_aruco#1] opened 2021-03-01 11:22 UTC
Thank you for putting this package together. I'm trying to visualize the pose array from detected fiducials in `/aruco_poses`, however the axis seems to be flipped in position and orientation. I tried to visualize both frames: camera and world, as shown in the launch file `ros2_aruco/launch/usb_camera_node.launch.py` but axis are still wrong. Are you publishing the opencv coord system? Thanks

**Comment by spragunr** [comment] 2021-03-01 12:29
I'm not sure what the issue could be.  The transforms have worked correctly for me, both for an external webcam and in simulation on a turtlebot3.  Maybe there is a problem with your camera .yaml file? This packages was developed under dashing.  Maybe the issue is related to using it in a more recent version of ROS2?

**Comment by Veilkrand** [comment] 2021-03-01 12:38
I'm using a raspberry pi camera v2 and this calibration file: https://raw.githubusercontent.com/UbiquityRobotics/raspicam_node/kinetic/camera_info/camerav2_1280x720.yaml

There may be a problem with matrices... Have you tried to use a raspicam?

**Comment by spragunr** [comment] 2021-03-02 12:58
I haven't, tried a pi camera, and I don't have access.  Good luck!  Let me know if you figure it out.

**Comment by Veilkrand** [comment] 2021-03-03 01:07
on second thought I don't think it should be related to the calibration file because the aruco library is able to identify and estimate the pose correctly. However the ros pose for me is using the wrong axis in rviz2, like the euler (openCV) to quaternion (ros) conversion is using the wrong axis order. 

Do you have a video of the visualization in rviz?

**Comment by Veilkrand** [comment] 2021-03-03 12:33
I migrated my package to ROS2 Foxy with correct RPY from OpenCV rotational vectors. If you want to try:
https://github.com/Veilkrand/ros2_markertracker

**Comment by spragunr** [comment] 2021-08-29 19:36
I just tested under foxy using the raspberry pi camera against this example:
<https://docs.opencv.org/3.4/d5/dae/tutorial_aruco_detection.html>
Here is the result:

![ros2_aruco_rviz](https://user-images.githubusercontent.com/4982892/131263147-2cd72997-6e32-499c-9378-d5cd8211c535.png)
vs
![singlemarkersaxes](https://user-images.githubusercontent.com/4982892/131263309-52fe44d0-7ee3-4d61-aead-ae7b7e41eac6.jpg)


The orientation of the axes look right to me, so I'm going to go ahead and close this issue.

**Closed as completed by spragunr** 2021-08-29 19:36 UTC
