### ISSUE TITLE
Can't execute aruco_node.py

### ISSUE THREAD

**Issue by jesusramondovale** [JMU-ROBOTICS-VIVA/ros2_aruco#2] opened 2023-01-18 12:23 UTC
I created the package and copid the python and setup, cfg files, colcon builded it succesfully, but when I run :

'ros2 run ros2_aruco aruco_node.py' it shows 'No Executable found'

I can succesfully run aruco_node.ccp (but it's a example of a print(Hello World) and it doesn't have anything to do with Aruco tracking) 

I need help. Thank you.

**Comment by jesusramondovale** [comment] 2023-01-19 10:26
The problem is that I can't install opencv-contrib-python module with pip nor pip3. It gives a connection error, same as if I try to install a bad module name, like if it doesn't exist

**Comment by jkaniuka** [comment] 2023-03-31 13:14
- The 'No Executable found' error is caused by the fact that you specified the .py extension in the command that starts the node. Instead, enter this command: `ros2 run ros2_aruco aruco_node` :+1:
- The problem with installing **opencv-contrib-python** may be because you already have **opencv-python** installed. Installing two packages of **opencv** may contradict each other and will not let the other one install. For more information, follow this [**link**](https://stackoverflow.com/questions/45972357/python-opencv-aruco-no-module-named-cv2-aruco?fbclid=IwAR3XXxXVMlYvgIpNHgO0fLzqkI-Mw1sARj1KOetuBnUpVxFI7AFipfPbamY).

**Comment by spragunr** [comment] 2023-07-06 13:48
Sounds like this wasn't actually an issue with the package, so I'm closing.  I hope you got it working.

**Closed as completed by spragunr** 2023-07-06 13:48 UTC
