### ISSUE TITLE
cannot build ros2_aruco 

### ISSUE THREAD

**Issue by nabeeljadoon** [JMU-ROBOTICS-VIVA/ros2_aruco#5] opened 2023-06-07 07:35 UTC
Hi I am running ros2 humble on Ubuntu 22.04 LTS. I am trying to build this ros2_aruco repo using colcon build but it gives me sterr error all the time. I have tried multipe options. I would appreciate your help in this regard. 

Could you tell me what is possibly wrong?
![image](https://github.com/JMU-ROBOTICS-VIVA/ros2_aruco/assets/19307307/2e5c9b19-eb11-4271-a45a-dcfc53939bc9)

**Comment by spragunr** [comment] 2023-06-07 14:55
It looks like it did build correctly.  Those are warnings.

Some of the warnings are related to a known issue with Humble:
https://github.com/ament/ament_cmake/issues/382

Others have been addressed in the recent humble release of this package.

**Closed as completed by spragunr** 2023-06-07 14:55 UTC

**Comment by nabeeljadoon** [comment] 2023-06-09 09:42
Actually it:s not built correctly. otherwise, ros2 run command should not show no package found.

**Comment by spragunr** [comment] 2023-06-12 16:03
In that case, I'm not sure what the issue is.  I tested recently on a fresh Humble install, and it worked OK for me.

**Comment by crytpy** [comment] 2023-06-26 01:46
> Actually it:s not built correctly. otherwise, ros2 run command should not show no package found.

The packages did build correctly as per your SS, you may have forgotten to source the installation folder.
